function createfigure(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Feb-2019 10:07:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','Y1',...
    'Color',[0.87058824300766 0.490196079015732 0]);
set(plot1(2),'DisplayName','Y2','Color',[0 0.498039215803146 0]);
set(plot1(3),'DisplayName','Y3','Color',[0 0 1]);
set(plot1(4),'DisplayName','Y4','Color',[1 0 0]);

% Create ylabel
ylabel('Y(t)');

% Create xlabel
xlabel('t');

% Create title
title('MA(4)');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-35 25]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Cambria','FontSize',14);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.78245485688911 0.793852434835854 0.100292824939613 0.0715434064435806],...
    'NumColumns',2);

